In [1]:
import numpy as np
import os

In [2]:
# hàm đọc một ma trận từ file txt
def read_matrix_from_file(path):
    if os.path.exists(path):
        with open(path, 'r') as reader:
            try:
                tmp = [[float(x) for x in row.split(' ')] for row in reader]
                matrix = np.array(tmp)
                
                if len(matrix.shape) == 2 and matrix.shape[0] == matrix.shape[1]:
                    return matrix
            except:
                pass
            
    return None

# hàm dùng kiểm tra một ma trận có phải là một ma trận đối xứng hay ko
def is_directional_graph(matrix):
    # nếu một ma trận bằng chính với ma trận chuyển vị của nó thì nó là một ma trận đối xứng
    return (matrix == matrix.T).all() 

# hàm in ra danh sách đỉnh kề của các đỉnh
def neighbors_of_vertices(matrix):
    no_vertices = matrix.shape[0] # lấy ra số lượng các đỉnh
    vertices = [[] for _ in range(no_vertices)]
    rows, cols = np.where(matrix != 0)
    
    for i in range(rows.size):
        vertices[rows[i]].append(cols[i])
    
    return [np.array(row) for row in vertices]

# hàm in ra số đỉnh bậc chẳn và bậc lẻ của ma trận:
def count_even_odd_vertices_each_vertices(lst_ndarr):
    no_vertices = len(lst_ndarr) # lấy ra số lượng các đỉnh
    no_even, no_odd, no_iso, no_pen = 0, 0, 0, 0 # lần lượt là số đỉnh bậc chẳn, lẻ, cô lập, treo
    
    for i in range(no_vertices):
        even = np.where(lst_ndarr[i] % 2 == 0)[0].size
        no_even += even
        no_odd += (lst_ndarr[i].size - even)
        no_iso += (lst_ndarr[i].size == 0)
        no_pen += (lst_ndarr[i].size == 1)
        
    return {
        'num_even': no_even,
        'no_odd': no_odd,
        'no_iso': no_iso,
        'no_pen': no_pen
    }

<hr>

In [3]:
matrix = read_matrix_from_file(r'data/data_2.txt')

print(matrix)

None


In [4]:
is_directional_graph(matrix)

AttributeError: 'NoneType' object has no attribute 'T'

In [76]:
vertices = neighbors_of_vertices(matrix)
vertices

[array([2, 3], dtype=int64),
 array([0, 2], dtype=int64),
 array([3], dtype=int64),
 array([], dtype=float64)]

In [77]:
count_even_odd_vertices_each_vertices(vertices)

{'num_even': 3, 'no_odd': 2, 'no_iso': 1, 'no_pen': 1}

In [6]:
rows, cols = np.where(matrix != 0)

In [7]:
rows, cols

array([0, 0, 1, 1, 2], dtype=int64)